name       : font-opendyslexic-otf
version    : 0.91.12
release    : 1
source     :
    - https://github.com/antijingoist/opendyslexic/archive/v0.91.12.tar.gz : d20d182fb7069023b8dbdf131bbe232093b4147dd4900e27c95b86d3ddfca34b
license    : OFL-1.1
summary    : OpenDyslexic, a typeface that uses typeface shapes & features to help offset some visual symptoms of Dyslexia.
component  : desktop.font
description: |
    OpenDyslexic, a typeface that uses typeface shapes & features to help offset some visual symptoms of Dyslexia.
install    : |
    fontdir=$installdir/usr/share/fonts/opentype/opendyslexic/
    install -dm644 $fontdir
    cp -R $workdir/compiled/*.otf $fontdir
    chmod -R 00644 $installdir